name: Deploy to Cyberfolks via FTPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        continue-on-error: true
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Cyberfolks via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: s113.cyber-folks.pl
          username: ${{ secrets.CYBERFOLKS_FTP_USERNAME }}
          password: ${{ secrets.CYBERFOLKS_FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: /domains/webgrove.pl/public_html/apps/tiling_img/
          protocol: ftps-legacy
          port: 21
          timeout: 90000
          log-level: verbose
          dangerous-clean-slate: true