name: Deploy to CyberFolks via lftp

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        continue-on-error: true  # Continue deployment even if tests fail
        
      - name: Build project
        run: npm run build
        
      - name: Install lftp
        run: sudo apt-get install -y lftp
        
      - name: Deploy via lftp
        run: |
          # Add verbose debugging to see connection details
          lftp -d -e "
          # Set general options
          set net:timeout 60;
          set net:max-retries 3;
          set net:reconnect-interval-base 5;
          
          # Disable SSL for regular FTP
          set ftp:ssl-allow no;
          
          # Connect to server
          open s113.cyber-folks.pl;
          
          # Login
          user ${{ secrets.CYBERFOLKS_FTP_USERNAME }} ${{ secrets.CYBERFOLKS_FTP_PASSWORD }};
          
          # Show remote directory to verify connection
          ls -la;
          
          # Upload files with mirror (sync) - only upload what has changed
          mirror --reverse --delete --verbose ./build/ /domains/webgrove.pl/public_html/apps/tiling_img/;
          
          # Exit
          quit"
        env:
          # Set environment variables for better security
          LFTP_PASSWORD: ${{ secrets.CYBERFOLKS_FTP_PASSWORD }}

      - name: Deployment status
        run: echo "Deployment completed. Check logs for any transfer errors."
