name: Deploy to Cyberfolks via SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        continue-on-error: true
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Cyberfolks via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.CYBERFOLKS_FTP_USERNAME }}
          server: ${{ secrets.CYBERFOLKS_FTP_SERVER }}
          port: 22 # Default SFTP port
          password: ${{ secrets.CYBERFOLKS_FTP_PASSWORD }}
          local_path: './build/*'
          remote_path: '/domains/webgrove.pl/public_html/apps/tiling_img/'
          sftp_only: true